name: Build SunamoDotnetCmdBuilder

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoDotnetCmdBuilder
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoDotnetCmdBuilder/SunamoDotnetCmdBuilder.csproj

    - name: Build
      run: dotnet build SunamoDotnetCmdBuilder/SunamoDotnetCmdBuilder.csproj --configuration Release --no-restore

  test:
    name: Test SunamoDotnetCmdBuilder.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoDotnetCmdBuilder.Tests/SunamoDotnetCmdBuilder.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoDotnetCmdBuilder.Tests/SunamoDotnetCmdBuilder.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoDotnetCmdBuilder.Tests/SunamoDotnetCmdBuilder.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
